# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DIrZ3efE3dbqYRVUNenCMzh_x-n_Y1Nu
"""

#prompt for users
noun= input("Noun: ")
verb= input("Verb: ")
adjective= input("Adjective: ")
favourite_place= input("favourite_place: ")

#Now let's create the story
madlib = f"""
On a bright and sunny day, a {adjective} {noun} woke up with a grand idea.
 It decided to {verb} all the way to {favourite_place}, hoping for an unforgettable
 adventure. Along the way, it met many curious creatures who cheered and laughed.
 The {noun} felt proud of its {adjective} journey, knowing it had done something
 extraordinary. By the time it reached {favourite_place},
everyone was talking about the amazing feat. It truly was a day to remember!"""

print("\nHere's your Madlib story: ")
print(madlib)


if st.button("Run"):
    result = f"Processed output for {input_value}"
    st.write(result)
